### ISSUE TITLE
Error compiling Less stylesheet

### ISSUE THREAD

**Issue by ryanspice** [taniarascia/new-moon-atom-syntax#2]
Not really sure what's happening here, after uninstalling and reinstalling it says the following: 

```
Error compiling Less stylesheet: D:\Programs\Atom\resources\app.asar\static\atom.less
Line number: 38
error evaluating function `fadeout`: color.toHSL is not a function
```

It seems to work, but if I restart the application it doesn't startup properly.

**Comment by taniarascia** [comment]
Very odd. I'm sorry you're having that issue! I'll try to reinstall it from the package and see if I can duplicate the issue.

**Comment by ryanspice** [comment]
I tried to disable some of my plugins because I thought it might have started happening after I added something, but it still seems to be giving the error.

**Comment by ryanspice** [comment]
Seems to be an issue with MetroUI https://github.com/Cirex/atom-metro-ui, 
Here's the error I get on startup.

```

Error
    at new Parser (D:\Programs\Atom\resources\app.asar\node_modules\less-cache\node_modules\less\lib\less\parser.js:333:27)
    at LessCache.module.exports.LessCache.parseLess (D:\Programs\Atom\resources\app.asar\node_modules\less-cache\lib\less-cache.js:244:16)
    at LessCache.module.exports.LessCache.cssForFile (D:\Programs\Atom\resources\app.asar\node_modules\less-cache\lib\less-cache.js:275:20)
    at LessCache.module.exports.LessCache.readFileSync (D:\Programs\Atom\resources\app.asar\node_modules\less-cache\lib\less-cache.js:263:19)
    at LessCompileCache.module.exports.LessCompileCache.read (D:\Programs\Atom\resources\app.asar\src\less-compile-cache.js:36:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (D:\Programs\Atom\resources\app.asar\src\theme-manager.js:310:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (D:\Programs\Atom\resources\app.asar\src\theme-manager.js:286:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (D:\Programs\Atom\resources\app.asar\src\theme-manager.js:203:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (D:\Programs\Atom\resources\app.asar\src\theme-manager.js:266:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (D:\Programs\Atom\resources\app.asar\src\theme-manager.js:261:19)


```

**Comment by shelbyKiraM** [comment]
+1 for this... It wouldn't let me launch unless I removed the theme ref from config.cson. Just opened to inspector window. And wouldn't let me uninstall so I had to delete the package folder... It still shows as installed, though.

**Comment by taniarascia** [comment]
Strange. I haven't been able to replicate this issue. I'll try installing a new Atom and installing the theme and see if it happens for me.

**Comment by taniarascia** [comment]
I've installed a new version of Atom, new, updated theme, and still can't replicate the issue. If it persists, let me know!
